server:
  port: 9001
  session:
    cookie:
      name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: sampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:9002/auth/oauth/token
      userAuthorizationUri: http://localhost:9002/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:9002/auth/user/me
spring:
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true